### ISSUE TITLE
support for node:12-alpine

### ISSUE THREAD

**Issue by anuragdalia** [mmdevries/uws#1]
It doesnt seem to work with docker when i use node:12-alpine as the base image 

it throws the required c++11 compiler error

although there seems to be a file named uws_linux_72 in dist/

**Comment by mmdevries** [comment]
I was able to reproduce the problem with node:12-alphine.
It seems that the uws_linux_72 module could not be loaded.
The following error occured:
**Error: Error relocating /root/workspace/test/node_modules/uws/dist/uws_linux_72.node: _ZN4node6AssertEPA4_KPKc: symbol not found**

I shall improve the feedback after such an error but I think this is an alpine issue. Some dependency was probably removed from the container to make it as small as possible.

**Comment by anuragdalia** [comment]
is there any way  i could fix it ?
because it seems to be working on node:10-alpine

**Comment by mmdevries** [comment]
I’m traveling at this moment. When I have some time I will try to discover what is missing.

**Comment by mmdevries** [comment]
To be honest I still not exactly know why this module will not run on node:12-alpine.
The following workaround seems to work.
I've added the pre-build modules for linux (uws version 2.2.1). Alpine uses musl (a light weight version of libc) so you need to create the following symbolic link before you run your application:
**ln -s /lib/libc.musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2**

If you build your own docker container you could add the line to your Dockerfile:
**RUN ln -s /lib/libc.musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2**

Please let me know if this works for you.

**Comment by mmdevries** [comment]
The issue is solved on version uws 2.3.1. The issue was triggered by using node 10 header files on the node 12 installation.
So, I've added the node 12 headers to the module and it runs now fine on the node:12-alpine docker container.
