### ISSUE TITLE
stable enough to use?

### ISSUE THREAD

**Issue by Succubussix** [mmdevries/uws#2]

**Comment by Succubussix** [comment]
aw it too slow I don't know what happens but the loading time now is bad :( like 10 seconds difference

**Comment by Succubussix** [comment]
from real-time to 10 seconds delay

**Comment by mmdevries** [comment]
To be honest, I have no idea what you mean.
Can you be more specific on your issue?

**Comment by Succubussix** [comment]
I use it on socket.io lately and it became slow. like 10 sec to do back and forth

**Comment by mmdevries** [comment]
Your question is if this module is stable enough. Well we use it for weeks already on our production platforms 24/7 without issues.

Do you now have suddenly an issue with this module? If so, which version of socket.io and uws are you using now? And on which version of socket.io and uws it was still fast?
