### ISSUE TITLE
yarn fails on latest node without --ignore-engines

### ISSUE THREAD

**Issue by Domiii** [mmdevries/uws#3]
## Problem

`yarn install` (or `yarn add github:mmdevries/uws#2.4.0`) will fail installation, citing:

> error uws@2.4.0: The engine "node" is incompatible with this module. Expected version ">=8.12.0 <13.0". Got "13.2.0"

## Solution

Just add the `--ignore-engines` flag to the `yarn` command, as `uws` works fine on latest node.

**Comment by mmdevries** [comment]
I have added support for node 13 in the 2.4.1 release. To be honest I haven't tested it.
Can you verify if this works for you?
Thanks.

**Comment by Domiii** [comment]
Sorry, I only realized today that `socket.io` (the reason why I actually added this dependency in the first place) is using `ws` by default, and I have not actually used `uws` yet (it only happened to have caused this problem when installing).

Unable to verify at this point :/
