### ISSUE TITLE
Bumped to 9.2.8??

### ISSUE THREAD

**Issue by naholyr** [mmdevries/uws#4]
Hi, you bumped from 2.9.7 to 9.2.8, I guess it was not intentional, but should we expect you fix it and go back to "2.9.x" or just go on with 9.x?

**Comment by naholyr** [comment]
Nevermind, I've just realised it's only the commit message which is wrong ;)

**Comment by mmdevries** [comment]
That was indeed a typo. It's now corrected.
Thanks for the feedback.
